spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/amovie?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  http:
    encoding:
      force: true
      charset: utf-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: /mappers/*.xml
logging:
  level:
    root: warn
pagehelper:
#  auto-dialect: mysql
#  reasonable: true
  helper-dialect: mysql
#  support-methods-arguments: true
